#!/bin/sh
mvn clean package
docker build -t aadityarp@7/GarmentsClientApp .
docker rm -f GarmentsClientApp 2>/dev/null || true
docker run -it --name GarmentsClientApp -p 8080:8080 --name GarmentsClientApp aadityarp@7/GarmentsClientApp
